apiVersion: v1
kind: Secret
metadata:
  name: kong-secret
  namespace: kong
type: Opaque
stringData:
  KONG_DATABASE: postgres # Kind of database kong using, we recommend using postgresql
  KONG_PG_HOST: <DATABASE_SERVER> # Database host
  KONG_PG_DATABASE: kong # Database name
  KONG_PG_USER: kong # Database user ( Must have permission to create database )
  KONG_PG_PASSWORD: kong # Database password
  KONG_PG_PORT: "5432" # Database port ( String )
  KONG_PROXY_LISTEN: 0.0.0.0:8000 reuseport backlog=16384, 0.0.0.0:8443 http2 ssl reuseport backlog=16384
  KONG_PORT_MAPS: 80:8000, 443:8443
  KONG_ADMIN_LISTEN: 0.0.0.0:8444
  KONG_STATUS_LISTEN: 0.0.0.0:8100
  KONG_NGINX_WORKER_PROCESSES: "2"
  KONG_KIC: "on"
  KONG_ADMIN_ACCESS_LOG: /dev/stdout
  KONG_ADMIN_ERROR_LOG: /dev/stderr
  KONG_PROXY_ERROR_LOG: /dev/stderr
  KONG_ROUTER_FLAVOR: traditional
---

apiVersion: v1
kind: Secret
metadata:
  name: konga-secret
  namespace: kong
type: Opaque
stringData:
  DB_ADAPTER: postgres # Kind of database kong using, we recommend using postgresql
  DB_HOST: <DB_SERVER> # Database host
  DB_DATABASE: konga # Database name
  DB_USER: kong # Database user
  DB_PASSWORD: kong # Database password
  DB_PORT: "5432" # Database port ( String )