apiVersion: v1
kind: Secret
metadata:
  name: kong-secret
  namespace: kong
type: Opaque
stringData:
  KONG_DATABASE: postgres # Kind of database kong using, we recommend using postgresql
  KONG_PG_HOST: <HOST> # Database host
  KONG_PG_DATABASE: <DB_NAME> # Database name
  KONG_PG_USER: <DB_USER> # Database user ( Must have permission to create database )
  KONG_PG_PASSWORD: <DB_PASSWORD> # Database password
  KONG_PG_PORT: <DB_PORT> # Database port ( String )

---

apiVersion: v1
kind: Secret
metadata:
  name: konga-secret
  namespace: kong
type: Opaque
stringData:
  DB_ADAPTER: postgres # Kind of database kong using, we recommend using postgresql
  DB_HOST: <HOST> # Database host
  DB_DATABASE: <DB_NAME> # Database name
  DB_USER: <DB_USER> # Database user
  DB_PASSWORD: <DB_PASSWORD> # Database password
  DB_PORT: <DB_PORT> # Database port ( String )